---
title: "ANA 515 Assignment 1-Lily"
author: "Qingyuan Li"
date: "2022-09-05"
output: word_document
theme: bootswatch:Flatly
---

```{r setup, include=FALSE}
#install.packages('tidyverse')
#install.packages('knitr')
#install.packages('bslib')
library(bslib)
library(knitr)
library(tidyverse)

library(ggplot2)
library(dplyr)
#library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)

```

```{r, include=FALSE}
url <- "https://raw.githubusercontent.com/fivethirtyeight/guns-data/master/full_data.csv"
data(package = "dplyr")
gun_deaths <- read.csv(url)

```

```{r, include=FALSE}

#library('knitr')
youth<- subset(gun_deaths,age<=65)


```


```{r,include=FALSE}
summary(youth)
```

```{r, include=FALSE}
numrows <- nrow(gun_deaths)
reducedrows<-nrow(gun_deaths)-nrow(youth)
```
We have data about `r numrows` individuals killed by guns. Only `r reducedrows` are older than 65. The distribution of the remainder is shown below:

```{r , echo=FALSE}
youth %>%
  ggplot(aes(age)) + geom_freqpoly(binwidth = 1)
```

```{r race-dist, echo=FALSE}
youth %>%
  ggplot(aes(fct_infreq(race) %>% fct_rev()))+geom_bar()+coord_flip()+labs(x="Victim race")

```
